language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install natsort matplotlib coveralls
  - pip install future
  - pip install Cython
  - pip install h5py
  - pip install scipy
  - pip install shapely
  - pip install pymysql
  - pip install nntoolkit
  - pip install flask flask_bootstrap
before_install:
  - sudo apt-get install libblas-dev liblapack-dev gfortran
  - sudo apt-get install python-scipy python-numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
script:
  - nosetests --with-cov --cover-package hwrt --logging-level=INFO
after_success:
  - coveralls
